name: check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: xschem-parser
          extraPullNames: crane
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - run: nix -vL --show-trace flake check
